name: new action

on:
  push:
    branches:
      - 'main'
      - 'test-action'
  pull_request:
    branches:
      - 'main'

jobs:
  newjob:
    runs-on: ubuntu-latest

  steps:
    - name: "print it works"
      run: echo "It works"
